// WordPress webpack config.
const defaultConfig = require('@wordpress/scripts/config/webpack.config');

// Plugins.
const RemoveEmptyScriptsPlugin = require('webpack-remove-empty-scripts');

// Utilities.
const path = require('path');

/**
 * Exports the Rockbase Child custom webpack config.
 *
 * @since 1.0.0
 */
module.exports = {
	...defaultConfig,
	...{
		entry: {
			// Load JS customizations
			'js/front': [path.resolve(process.cwd(), 'src/js/front/', '_index.js')],
			'js/editor': [path.resolve(process.cwd(), 'src/js/editor/', '_index.js')],
		},
		plugins: [
			// Include WP's plugin config.
			...defaultConfig.plugins,
			// Removes the empty `.js` files generated by webpack but
			// sets it after WP has generated its `*.asset.php` file.
			new RemoveEmptyScriptsPlugin({
				stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS
			})
		]
	}
};